#      _    _                  _                 _ 
#     | |  | |                | |               | |
#     | |__| |_   _ _ __  _ __| | __ _ _ __   __| |
#     |  __  | | | | '_ \| '__| |/ _` | '_ \ / _` |
#     | |  | | |_| | |_) | |  | | (_| | | | | (_| |
#     |_|  |_|\__, | .__/|_|  |_|\__,_|_| |_|\__,_|
#              __/ | |                             
#             |___/|_|                             

source = ~/.config/hypr/configs/startup.conf
source = ~/.config/hypr/configs/monitors.conf
source = ~/.config/hypr/configs/keybinds.conf
source = ~/.config/hypr/configs/defaults.conf
source = ~/.config/hypr/configs/environment.conf
source = ~/.config/hypr/configs/input.conf
source = ~/.config/hypr/configs/animations.conf
source = ~/.config/hypr/configs/general.conf
source = ~/.config/hypr/configs/decoration.conf
source = ~/.config/hypr/configs/rules.conf
source = ~/.config/hypr/configs/plugins.conf

# if dolphin broken run
# XDG_MENU_PREFIX=arch- kbuildsycoca6
