general {
    ignore_dbus_inhibit = false             # whether to ignore dbus-sent idle-inhibit requests (used by e.g. firefox or steam)
    lock_cmd = pidof hyprlock || hyprlock   # avoid starting multiple hyprlock instances.
    before_sleep_cmd = loginctl lock-session    # lock before suspend.
    after_sleep_cmd = hyprctl dispatch dpms on  # to avoid having to press a key twice to turn on the display.
    after_sleep_cmd = sh -c "hyprctl reload; sleep 0.2; hyprctl reload"
    # lock_cmd = notify-send "lock!"          # dbus/sysd lock command (loginctl lock-session) 
    # unlock_cmd = notify-send "unlock!"      # same as above, but unlock
}

listener {
    timeout = 900 #? 15 minutes
    on-timeout = brightnessctl set 50% && ddcutil setvcp 10 - 50 --bus 2
    on-resume = brightnessctl set 100% && ddcutil setvcp 10 + 50 --bus 2
}

listener {
    timeout = 1800 #? 30 minutes
    on-timeout = brightnessctl set 1% && ddcutil setvcp 10 - 99 --bus 2 && hyprlock
    on-resume = brightnessctl set 100% && ddcutil setvcp 10 + 99 --bus 2
}


listener {
    timeout = 3600 #? 1 hour
    on-timeout = systemctl suspend
}

