#      _____                           _   _             
#     |  __ \                         | | (_)            
#     | |  | | ___  ___ ___  _ __ __ _| |_ _  ___  _ __  
#     | |  | |/ _ \/ __/ _ \| '__/ _` | __| |/ _ \| '_ \ 
#     | |__| |  __/ (_| (_) | | | (_| | |_| | (_) | | | |
#     |_____/ \___|\___\___/|_|  \__,_|\__|_|\___/|_| |_|
                                                                                          
decoration {
    rounding = 10
    rounding_power = 2

    active_opacity = 1.0
    inactive_opacity = 1.0

    shadow { #TODO customize later
        enabled = true
        range = 4
        render_power = 3
        color = rgba(1a1a1aee)
    }

    # blur = true
    # blur_size = 6
    # blur_passes = 3
    blur {  #! uncomment top doesn't work
        enabled = true
        size = 3
        passes = 1
        vibrancy = 0.1696
    }

}
