#      ______            _                                      _       
#     |  ____|          (_)                                    | |      
#     | |__   _ ____   ___ _ __ ___  _ __  _ __ ___   ___ _ __ | |_ ___ 
#     |  __| | '_ \ \ / / | '__/ _ \| '_ \| '_ ` _ \ / _ \ '_ \| __/ __|
#     | |____| | | \ V /| | | | (_) | | | | | | | | |  __/ | | | |_\__ \
#     |______|_| |_|\_/ |_|_|  \___/|_| |_|_| |_| |_|\___|_| |_|\__|___/

env = XCURSOR_SIZE,48 
env = HYPRCURSOR_SIZE,48

#* KDE STUFF
env = QT_QPA_PLATFORMTHEME,kde
env = XDG_SESSION_DESKTOP,KDE
env = XDG_MENU_PREFIX,arch-


env = LIBVA_DRIVER_NAME,nvidia
env = __GLX_VENDOR_LIBRARY_NAME,nvidia

#? not sure if need
# env = LIBINPUT_ACCEL_PROFILE,adaptive
# env = LIBINPUT_ACCEL_SPEED,0.5