#       _____                           _ 
#      / ____|                         | |
#     | |  __  ___ _ __   ___ _ __ __ _| |
#     | | |_ |/ _ \ '_ \ / _ \ '__/ _` | |
#     | |__| |  __/ | | |  __/ | | (_| | |
#      \_____|\___|_| |_|\___|_|  \__,_|_|

general {
    gaps_in = 5
    gaps_out = 10
    border_size = 2
    allow_tearing = true
    layout = dwindle
    resize_on_border = false
    # col.active_border = rgba(88c0d0ee) rgba(5e81acee) 45deg
    col.active_border = rgb(81a1c1)
    col.inactive_border = rgba(4c566aaa)
}

group {
    # col.border_active = rgba(88c0d0ee) rgba(5e81acee) 45deg
    col.border_active = rgb(81a1c1)
    col.border_inactive = rgba(4c566aaa)

    groupbar {
        render_titles = true
        font_size = 14
        font_family = JetBrains Mono Nerd Font
        font_weight_active = bold
        rounding_power = 2.0
        
        text_color = rgba(88c0d0ee)
        text_color_inactive = rgba(81a1c1ff)

        height = 14
        indicator_height = 1
        indicator_gap = 0

        gaps_in = 2
        gaps_out = 2

        col.active = rgba(00000000)
        col.inactive = rgba(00000000)
    }
}

#? "Smart gaps" / "No gaps when only"
# workspace = w[tv1]s[false], gapsout:0, gapsin:0
# workspace = f[1]s[false], gapsout:0, gapsin:0
# windowrule = border_size 0, match:float 0, match:workspace w[tv1]s[false]
# windowrule = rounding 0, match:float 0, match:workspace w[tv1]s[false]
# windowrule = border_size 0, match:float 0, match:workspace f[1]s[false]
# windowrule = rounding 0, match:float 0, match:workspace f[1]s[false]

dwindle {
    pseudotile = true
    preserve_split = true
}

master {
    new_status = master
}

misc {
    force_default_wallpaper = 0 # Set to 0 or 1 to disable the anime mascot wallpapers
    disable_hyprland_logo = true # If true disables the random hyprland logo / anime girl background.
    focus_on_activate = true
}

cursor {
    no_hardware_cursors = true
}

