#      _____                   _   
#     |_   _|                 | |  
#       | |  _ __  _ __  _   _| |_ 
#       | | | '_ \| '_ \| | | | __|
#      _| |_| | | | |_) | |_| | |_ 
#     |_____|_| |_| .__/ \__,_|\__|
#                 | |              
#                 |_|              

input {
    kb_layout = us
    numlock_by_default = true

    follow_mouse = 1
    sensitivity = 0 # -1.0 - 1.0, 0 means no modification.

    touchpad {
        natural_scroll = true
        scroll_factor = 0.4
        drag_lock = 1
    }
}

#? touchpad gestures
gesture = 3, horizontal, workspace
gesture = 3, up, fullscreen, maximize
gesture = 3, pinch, float

# device {
#     name = etps/2-elantech-touchpad
#     accel_profile = adaptive
#     sensitivity = 3.5 # orig 0.0
# }

device {
    name = logitech-g403-hero-gaming-mouse
    accel_profile = flat
    sensitivity = 0.0
}

device {
    name = msnb0001:00-04f3:30aa-touchpad
    accel_profile = adaptive
    sensitivity = 0.0
    enabled = true
}

device {
    name = dualsense-wireless-controller-touchpad
    enabled = false
}

device {
    name = sony-interactive-entertainment-dualsense-wireless-controller-touchpad
    enabled = false
}

device {
    name = compx-mad-8k-dongle-mouse
    accel_profile = flat
    sensitivity = 0.0
}

device {
    name = compx-mad-8k-dongle-1
    accel_profile = flat
    sensitivity = 0.0
}

device {
    name = compx-mad-r-major+-1
    accel_profile = flat
    sensitivity = 0.0
}
