#      _____  _             _           
#     |  __ \| |           (_)          
#     | |__) | |_   _  __ _ _ _ __  ___ 
#     |  ___/| | | | |/ _` | | '_ \/ __|
#     | |    | | |_| | (_| | | | | \__ \
#     |_|    |_|\__,_|\__, |_|_| |_|___/
#                      __/ |            
#                     |___/             

plugin {
    hyprexpo {
        columns = 3
        gap_size = 5
        bg_col = rgb(111111)
        # workspace_method = center current # [center/first] [workspace] e.g. first 1 or center m+1
        workspace_method = first 1 # [center/first] [workspace] e.g. first 1 or center m+1
        skip_empty = true

        gesture_distance = 300 # how far is the "max" for the gesture
    }
}