#      _____       _           
#     |  __ \     | |          
#     | |__) |   _| | ___  ___ 
#     |  _  / | | | |/ _ \/ __|
#     | | \ \ |_| | |  __/\__ \
#     |_|  \_\__,_|_|\___||___/

# ? WINDOWRULES
#* MUSIC APPS
windowrule = workspace special:extra, match:class ^(spotify)$
windowrule = workspace special:extra, match:class ^(com.github.th_ch.youtube_music)$
windowrule = workspace special:extra, match:class ^(com.github.neithern.g4music)$
windowrule = workspace special:extra, match:title ^(Tauon)$
windowrule = workspace special:extra, match:title ^(Recordbox)$

#* GAME WORKSPACE
windowrule = workspace 3, float off, match:class ^(steam)$
windowrule = workspace 3, float on, size 350 700, center on, border_size 0, match:title ^(Friends List)$

windowrule = workspace 3, match:class ^(Ryujinx)$
windowrule = workspace 3, match:class ^(org.citron_emu.citron)$
windowrule = workspace 3, match:class ^(osu!)$
windowrule = fullscreen on, match:class ^(gamescope)$
windowrule = fullscreen on, match:class ^(steam_proton)$

windowrule = float on, stay_focused true, match:title ^()$, match:class ^(steam)$
windowrule = float on, min_size 1 1, match:title ^()$, match:class ^(steam)$ 

#* ZEN PIP
windowrule = float on, center on, pin on, match:class ^(zen)$, match:title ^(Picture-in-Picture)$

#* APP FIXES
windowrule = float on, center on, match:class ^(org.kde.kdeconnect.app)$
windowrule = float on, center on, match:class ^(org.kde.kdeconnect.daemon)$
windowrule = float on, center on, match:class ^(kitty)$, match:title ^(arch-update)$
windowrule = float on, size 700 540, center on, match:class ^(xdg-desktop-portal-gtk)$
windowrule = border_size 0, match:class ^(zoom)$
windowrule = center on, match:class ^(DesktopEditors)$
windowrule = float on, center on, size 700 540, match:class ^(hyprland-share-picker)$

# ------------------------------

#* WINBOAT
windowrule = suppress_event fullscreen maximize activate activatefocus, match:class ^winboat-.*$

windowrule = no_anim on, match:class ^winboat-.*$
windowrule = rounding 0, match:class ^winboat-.*$
windowrule = no_shadow on, match:class ^winboat-.*$
windowrule = no_blur on, match:class ^winboat-.*$
windowrule = xray 0, match:class ^winboat-.*$
windowrule = opaque on, match:class ^winboat-.*$
windowrule = no_dim on, match:class ^winboat-.*$
windowrule = force_rgbx on, allows_input on, match:class ^winboat-.*$

# ------------------------------

#? WAYBAR UTILS RULES
#* BLUEBERRY
windowrule = float on, center on, size 480 540, match:class ^(?i:blueberry\.py)$
#* NETWORK MANAGER
windowrule = float on, center on, size 440 540, match:title ^(.*Network Manager.*)$
# * PAVUCONTROL
windowrule = float on, size 480 540, center on, match:class ^(org.pulseaudio.pavucontrol)$
# * DDCUI
windowrule = float on, size 480 360, center on, match:class ^(ddcui)$

# ------------------------------


# ? MONITOR SETUP
workspace = 1, monitor:HDMI-A-1, persistent:true
workspace = 2, monitor:HDMI-A-1, persistent:true
workspace = 3, monitor:HDMI-A-1, persistent:true

workspace = 4, monitor:eDP-2, persistent:true
workspace = 5, monitor:eDP-2, persistent:true
workspace = 6, monitor:eDP-2, persistent:true

# workspace = 1, monitor:DP-1, persistent:true
# workspace = 2, monitor:DP-1, persistent:true
# workspace = 3, monitor:DP-1, persistent:true

# ------------------------------

# ? WORKSPACE LAYOUTS
workspace = 2, layout:scrolling
workspace = s[true], extra, layout:scrolling

# ------------------------------

# ? VICINAE RULES
layerrule {
    name = vicinae-blur
    blur = on
    ignore_alpha = 0
    match:namespace = vicinae
}