#       _____ _             _               
#      / ____| |           | |              
#     | (___ | |_ __ _ _ __| |_ _   _ _ __  
#      \___ \| __/ _` | '__| __| | | | '_ \ 
#      ____) | || (_| | |  | |_| |_| | |_) |
#     |_____/ \__\__,_|_|   \__|\__,_| .__/ 
#                                    | |    
#                                    |_|    

exec-once = swaync &
exec-once = waybar &
exec-once = awww-daemon &
exec-once = snappy-switcher --daemon
exec-once = vicinae server
exec-once = hypridle
exec-once = /usr/lib/polkit-kde-authentication-agent-1 #? Auth Agent
exec-once = hyprpm reload
exec-once = hyprctl dispatch workspace 1 #? for dual monitor setup
exec-once = ~/.config/hypr/scripts/refratechange.sh #TODO fix not working during startup
exec-once = usr/lib/kdeconnectd
exec-once = kdeconnect-indicator

#* OLD CLIPBOARD STUFF
# exec-once = wl-paste --type text --watch clipvault store # Forward text data
# exec-once = wl-paste --type image --watch clipvault store # Forward raw image data

# # Forward all data, ignoring text that starts with "<meta http-equiv="
# exec-once = wl-paste --watch clipvault store --ignore-pattern '^<meta http-equiv='
# exec-once = wl-clip-persist --clipboard regular











